trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Build and Deploy DEV"
    jobs:
    - job: 'TerraformInitAndValidate'
      displayName: "Terraform install, Init and Validate" 
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformCLI@0
        inputs:
          command: 'workspace'
          allowTelemetryCollection: true
          workspaceName: 'dev'
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          backendType: 'azurerm'
          backendServiceArm: 'Azure subscription 1(1)(f4210fd4-9a8e-484e-b3ab-bf706abb3785)'
          backendAzureRmSubscriptionId: 'f4210fd4-9a8e-484e-b3ab-bf706abb3785'
          backendAzureRmResourceGroupName: 'tfstate'
          backendAzureRmStorageAccountName: 'dentfstate'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'apply'
          environmentServiceName: 'Azure subscription 1(1)(f4210fd4-9a8e-484e-b3ab-bf706abb3785)'
          providerAzureRmSubscriptionId: 'f4210fd4-9a8e-484e-b3ab-bf706abb3785'
          commandOptions: '--auto-approve'
          allowTelemetryCollection: true
  - stage: Build on PR
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
    - job: 'TerraformInitAndValidate'
      displayName: "Terraform install, Init and Validate" 
      steps:
      - task: TerraformCLI@0
        inputs:
          command: 'workspace'
          allowTelemetryCollection: true
          workspaceName: 'dev'
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          backendType: 'azurerm'
          backendServiceArm: 'Azure subscription 1(1)(f4210fd4-9a8e-484e-b3ab-bf706abb3785)'
          backendAzureRmSubscriptionId: 'f4210fd4-9a8e-484e-b3ab-bf706abb3785'
          backendAzureRmResourceGroupName: 'tfstate'
          backendAzureRmStorageAccountName: 'dentfstate'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'plan'
          allowTelemetryCollection: true
          publishPlanResults: 'tfplan'
      